# [dbo].[Automobile]

In [0]:
USE [18ip12]
GO

In [0]:
/****** Object:  Table [dbo].[Automobile]    Script Date: 27.01.2022 12:18:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Automobile](
	[id_automobile] [int] IDENTITY(1,1) NOT NULL,
	[rent_cost_per_dat_auto] [int] NULL,
	[insuarance_price] [int] NULL,
	[id_model] [int] NULL,
	[color_auto] [nvarchar](100) NULL,
	[year_of_manufacture_auto] [int] NULL,
	[number_auto] [nvarchar](100) NULL,
 CONSTRAINT [PK_Automobile] PRIMARY KEY CLUSTERED 
(
	[id_automobile] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Clients]

In [0]:
/****** Object:  Table [dbo].[Clients]    Script Date: 27.01.2022 12:18:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[id_cle] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](100) NULL,
	[surname] [nvarchar](100) NULL,
	[patronymic] [nvarchar](100) NULL,
	[passport_seri] [int] NULL,
	[passport_numb] [int] NULL,
 CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED 
(
	[id_cle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Model]

In [0]:
/****** Object:  Table [dbo].[Model]    Script Date: 27.01.2022 12:18:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Model](
	[id_mod] [int] IDENTITY(1,1) NOT NULL,
	[title_model] [nvarchar](100) NULL,
 CONSTRAINT [PK_Model] PRIMARY KEY CLUSTERED 
(
	[id_mod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Renta]

In [0]:
/****** Object:  Table [dbo].[Renta]    Script Date: 27.01.2022 12:18:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Renta](
	[id_rent] [int] IDENTITY(1,1) NOT NULL,
	[date_start_ren] [date] NULL,
	[id_clients] [int] NULL,
	[id_auto] [int] NULL,
	[number_of_days] [int] NULL,
 CONSTRAINT [PK_Renta] PRIMARY KEY CLUSTERED 
(
	[id_rent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK_Automobile_Model]

In [0]:
ALTER TABLE [dbo].[Automobile]  WITH CHECK ADD  CONSTRAINT [FK_Automobile_Model] FOREIGN KEY([id_model])
REFERENCES [dbo].[Model] ([id_mod])
GO
ALTER TABLE [dbo].[Automobile] CHECK CONSTRAINT [FK_Automobile_Model]
GO

# [FK_Renta_Automobile]

In [0]:
ALTER TABLE [dbo].[Renta]  WITH CHECK ADD  CONSTRAINT [FK_Renta_Automobile] FOREIGN KEY([id_auto])
REFERENCES [dbo].[Automobile] ([id_automobile])
GO
ALTER TABLE [dbo].[Renta] CHECK CONSTRAINT [FK_Renta_Automobile]
GO

# [FK_Renta_Clients]

In [0]:
ALTER TABLE [dbo].[Renta]  WITH CHECK ADD  CONSTRAINT [FK_Renta_Clients] FOREIGN KEY([id_clients])
REFERENCES [dbo].[Clients] ([id_cle])
GO
ALTER TABLE [dbo].[Renta] CHECK CONSTRAINT [FK_Renta_Clients]
GO